### ISSUE TITLE
Implement Final Style

### ISSUE THREAD

**Issue by FalconLuma** [FalconLuma/-DECO38010--VillersBoysII#1]
Implement the design from the high fidelity prototype in the app.

**Pages:**
- [x] driving_page
- [x] home_page
- [x] main_page
- [x] memory_test
- [x] memory_test_intro
- [x] newStart
- [x] profile_page
- [x] questionaire_start
- [x] questionaire_test
- [x] reaction_time_intro
- [x] reaction_time_test1
- [x] reaction_time1
- [x] results_page
- [x] settings_page
- [x] StartCalibrate

**Comment by FalconLuma** [comment]
I'll work on the following pages:

- [x] driving_page
- [x] home_page
- [x] results_page
- [x] main_page
- [x] settings_page

**Comment by Isaac-F** [comment]
I'll work on the following pages:

- [x] profile_page
- [x] memory_test
- [x] memory_test_intro
- [x] reaction_test_intro
- [x] reaction_time1
- [x] questionaire_start
- [x] newStart
- [x] StartCalibrate
- [x] reaction_time_test_1
- [x] questionaire_test

**Comment by Isaac-F** [comment]
I just pushed an update to the main_page that updates the AppBar for the profile and seatbelt pages.
